.TH "adminWindow" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adminWindow \- the admin window of the app  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBINHERIT_BASE_WIN\fP \fBLoginWindow\fP \fBloginWindow\fP"
.br
.RI "the window to login to the admin menu "
.ti -1c
.RI "GtkEntry * \fBpropertyNameInput\fP"
.br
.ti -1c
.RI "GtkEntry * \fBbaseDiscountInput\fP"
.br
.ti -1c
.RI "GtkLabel * \fBtotalMoneyLabel\fP"
.br
.ti -1c
.RI "GtkLabel * \fBtotalNightsLabel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the admin window of the app 
.SH "Field Documentation"
.PP 
.SS "GtkEntry* baseDiscountInput"

.SS "\fBINHERIT_BASE_WIN\fP \fBLoginWindow\fP loginWindow"

.PP
the window to login to the admin menu 
.SS "GtkEntry* propertyNameInput"

.SS "GtkLabel* totalMoneyLabel"

.SS "GtkLabel* totalNightsLabel"


.SH "Author"
.PP 
Generated automatically by Doxygen for AirUCCS from the source code\&.
