.TH "app" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app \- the main struct containing all app info that we need  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBINHERIT_BASE_WIN\fP GtkApplication * \fBapp\fP"
.br
.ti -1c
.RI "\fBProperty\fP \fBproperty\fP"
.br
.ti -1c
.RI "\fBCustomerWindow\fP \fBcustomerWindow\fP"
.br
.ti -1c
.RI "\fBAdminWindow\fP \fBadminWindow\fP"
.br
.ti -1c
.RI "\fBConfigWindow\fP \fBconfigWindow\fP"
.br
.ti -1c
.RI "\fBReviewWindow\fP \fBreviewWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the main struct containing all app info that we need 
.SH "Field Documentation"
.PP 
.SS "\fBAdminWindow\fP \fBadminWindow\fP"
the admin Window 
.SS "\fBINHERIT_BASE_WIN\fP GtkApplication* \fBapp\fP"

.SS "\fBConfigWindow\fP \fBconfigWindow\fP"
the config window 
.SS "\fBCustomerWindow\fP \fBcustomerWindow\fP"
the main window 
.SS "\fBProperty\fP \fBproperty\fP"
the property 
.SS "\fBReviewWindow\fP \fBreviewWindow\fP"
the review window 

.SH "Author"
.PP 
Generated automatically by Doxygen for AirUCCS from the source code\&.
