.TH "configWindow" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configWindow \- the config window of the app  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
the config window of the app 

.SH "Author"
.PP 
Generated automatically by Doxygen for AirUCCS from the source code\&.
