.TH "customerWindow" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
customerWindow \- the customer window of the app  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBINHERIT_BASE_WIN\fP GtkWidget * \fBpriceRendererWindow\fP"
.br
.ti -1c
.RI "GtkWidget * \fBinputEntry\fP"
.br
.ti -1c
.RI "GtkWidget * \fBreviewTable\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgrid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the customer window of the app 
.SH "Field Documentation"
.PP 
.SS "GtkWidget* grid"
the review table 
.SS "GtkWidget* inputEntry"
the entry widget for the input of number of night 
.SS "\fBINHERIT_BASE_WIN\fP GtkWidget* priceRendererWindow"
the label widget to store price within 
.SS "GtkWidget* reviewTable"
the review table 

.SH "Author"
.PP 
Generated automatically by Doxygen for AirUCCS from the source code\&.
