.TH "location" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
location \- the location of the property @initalizer: initLocation  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBaddress\fP [\fBSTRING_SIZE\fP]"
.br
.ti -1c
.RI "int \fBlat\fP"
.br
.ti -1c
.RI "int \fBlon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the location of the property @initalizer: initLocation 
.SH "Field Documentation"
.PP 
.SS "char address[\fBSTRING_SIZE\fP]"

.SS "int lat"

.SS "int lon"


.SH "Author"
.PP 
Generated automatically by Doxygen for AirUCCS from the source code\&.
