.TH "md_readme" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_readme \- readme 
.PP
I have provided all dependancies that should be required within the libs and gtk folders\&. So it should be easy to build and run\&. If for some reason you do hit a dependancy issue\&. Unix is very easy to get gtk set up on so: for macOs go the this link and follow the getting started steps: https://www.gtk.org/docs/installations/macos/ they havea fully built install script that handles everything for you for linux https://www.gtk.org/docs/installations/linux/ go to here and follow install guide or just clone the repo for it\&.
.PP
You can compile with this command if you want to\&.: gcc $( pkg-config --cflags gtk4 ) -o example-0 \fBmain\&.c\fP $( pkg-config --libs gtk4 )
.PP
!!WARNING only minimize the windows of the app, once one is closed it will crash if reopened due to some weirdness with gtk that I didn't have time to look into
.PP
The RSA key gen is so very close to functional, the public key is correct and works, but the private key's exponent is consistantly off by around 10 which is a lot since its an exponent, but I cannot figure out how to fix my math to get it working\&. Its something with the mod inverse function that I cannot figure out how to fix\&. 
