.TH "reviewWindow" 3 "Version 1" "AirUCCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reviewWindow \- the review Window of the app  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBINHERIT_BASE_WIN\fP GtkEntry * \fBinputs\fP [\fBNUMBER_OF_REVIEW_CATS\fP]"
.br
.ti -1c
.RI "GtkButton * \fBsubmitBtn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the review Window of the app 
.SH "Field Documentation"
.PP 
.SS "\fBINHERIT_BASE_WIN\fP GtkEntry* inputs[\fBNUMBER_OF_REVIEW_CATS\fP]"

.SS "GtkButton* submitBtn"


.SH "Author"
.PP 
Generated automatically by Doxygen for AirUCCS from the source code\&.
